version: "3.9"
services:
  app:
    build: .
    # command: poetry run flask run -h 0.0.0.0
    # image: simple2b/sc_project
    command: ./start_server.sh
    restart: always
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:5000
    depends_on:
      - db
  
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./:/app
      - db_data:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db
    ports:
      - 127.0.0.1:${DB_LOCAL_PORT}:5432

volumes:
  db_data: