"""description nullable

Revision ID: 09402c1abe6d
Revises: 80dce468f321
Create Date: 2022-06-20 15:06:08.441024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09402c1abe6d'
down_revision = '80dce468f321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
