"""new plab_date fields

Revision ID: 174cc98ad822
Revises: ad508330b4ce
Create Date: 2022-06-22 12:35:39.521870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174cc98ad822'
down_revision = 'ad508330b4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_dates', sa.Column('note', sa.String(length=256), nullable=True))
    op.add_column('plan_dates', sa.Column('reason', sa.String(length=256), nullable=True))
    op.add_column('plan_dates', sa.Column('responsible', sa.String(length=128), nullable=True))
    op.add_column('plan_dates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan_dates', 'users', ['user_id'], ['id'])
    op.drop_column('works', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('note', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plan_dates', type_='foreignkey')
    op.drop_column('plan_dates', 'user_id')
    op.drop_column('plan_dates', 'responsible')
    op.drop_column('plan_dates', 'reason')
    op.drop_column('plan_dates', 'note')
    # ### end Alembic commands ###
