"""add ppc_type

Revision ID: 33dacd319465
Revises: 6207acb02f48
Create Date: 2022-06-07 15:45:34.270713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33dacd319465"
down_revision = "6207acb02f48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE ppctype AS ENUM('info', 'docs', 'quality', 'atp', 'hod')")
    op.add_column(
        "works",
        sa.Column(
            "ppc_type",
            sa.Enum("info", "docs", "quality", "atp", "hod", name="ppctype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("works", "ppc_type")
    # ### end Alembic commands ###
