"""is_completed

Revision ID: 4a9c2394956b
Revises: 174cc98ad822
Create Date: 2022-06-22 20:03:48.338224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9c2394956b'
down_revision = '174cc98ad822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.drop_column('works', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('complete', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_column('works', 'is_completed')
    # ### end Alembic commands ###
