"""deleted to WorkPackage

Revision ID: 6207acb02f48
Revises: 4cddeb445815
Create Date: 2022-06-06 12:56:20.655833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6207acb02f48'
down_revision = '4cddeb445815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_packages', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_packages', 'deleted')
    # ### end Alembic commands ###
