"""location_id 

Revision ID: 6c85f9b7a2e2
Revises: 4a2e249554e7
Create Date: 2022-06-15 16:12:12.162284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c85f9b7a2e2'
down_revision = '4a2e249554e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('location_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'location_id')
    # ### end Alembic commands ###
