"""add wp_id for user

Revision ID: 80dce468f321
Revises: a748991dddf7
Create Date: 2022-06-20 09:51:05.844940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dce468f321'
down_revision = 'a748991dddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wp_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wp_id')
    # ### end Alembic commands ###
