"""add complete

Revision ID: a748991dddf7
Revises: 95b60a85121c
Create Date: 2022-06-16 20:13:28.972085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a748991dddf7'
down_revision = '95b60a85121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('complete', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'complete')
    # ### end Alembic commands ###
