"""date planed to work

Revision ID: e046ae93bac2
Revises: 86aca79dc171
Create Date: 2022-06-23 19:51:50.953343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e046ae93bac2'
down_revision = '86aca79dc171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('date_planed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'date_planed')
    # ### end Alembic commands ###
